<?php

/**
 * @file
 * Primary module hooks for LocalGov Replicate module.
 */

use Drupal\localgov_roles\RolesHelper;

/**
 * Implements hook_localgov_roles_default().
 */
function localgov_replicate_localgov_roles_default(): array {
  $perms = [
    RolesHelper::EDITOR_ROLE => [
      'replicate entities',
    ],
  ];

  return $perms;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function localgov_replicate_menu_local_tasks_alter(&$data, $route_name): void {
  $routes = [
    'entity.node.canonical',
    'entity.node.replicate',
    'entity.node.edit_form',
    'entity.node.book_outline_form',
    'entity.node.delete_form',
    'entity.node.version_history',
    'entity.node.entity_hierarchy_reorder',
    'entity.node.preview_link_generate',
    'entity.node.scheduled_transitions',
  ];

  if (in_array($route_name, $routes)) {
    $data['tabs'][0]['replicate_ui.local_tasks:entity.node.replicate']['#link']['title'] = t('Clone');
  }
}
